[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "@diamond/contracts=lib/diamond-2/contracts",
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
